name: Bug report
description: Report a reproducible bug
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include concrete CLI commands
      placeholder: |
        1. microcms ...
        2. microcms ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: node version, OS, CLI version
